spring.application.name=demo
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.lemqltbwinycopxtymqu
spring.datasource.password=AgrohubSupDB

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true